spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      springframework:
        security: DEBUG

    com:
      example:
        authservice: DEBUG
server:
  port: 8080

